In [2]:
import tensorflow as tf

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()

In [4]:
vector = tf.constant([1,2,3,4])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [5]:
scalar = tf.constant(3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [7]:
matrix = tf.random.Generator.from_seed(3)
matrix = matrix.normal(shape=(3,2))
matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.43640924, -1.9633987 ],
       [-0.06452483, -1.056841  ],
       [ 1.0019137 ,  0.6735137 ]], dtype=float32)>

2. Find the shape, rank and size of the tensors you created in 1.

In [8]:
tf.shape(scalar)

<tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>

In [9]:
tf.shape(vector)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([4], dtype=int32)>

In [10]:
tf.shape(matrix)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [11]:
tf.rank(scalar)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [12]:
tf.rank(vector)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [13]:
tf.rank(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [14]:
tf.size(scalar)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [15]:
tf.size(vector)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [16]:
tf.size(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

3. Create two tensors containing random values between 0 and 1 with shape [5, 300]


In [18]:
tf1 = tf.random.uniform(shape=[5,300], minval=0, maxval=1)
tf1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.31269336, 0.00539625, 0.04541814, ..., 0.6895721 , 0.91105616,
        0.9651989 ],
       [0.2686497 , 0.8777261 , 0.658779  , ..., 0.9153099 , 0.88586986,
        0.5596211 ],
       [0.8828579 , 0.62549007, 0.95173204, ..., 0.4642074 , 0.7283939 ,
        0.09631729],
       [0.3974831 , 0.00961459, 0.4709952 , ..., 0.4502647 , 0.6250684 ,
        0.21976388],
       [0.1864345 , 0.7747674 , 0.17867434, ..., 0.80021775, 0.01815736,
        0.04299021]], dtype=float32)>

In [19]:
tf2 = tf.random.uniform(shape=[5,300], minval=0, maxval = 1)
tf2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[7.20492482e-01, 7.70267487e-01, 7.80865669e-01, ...,
        1.16231561e-01, 5.88883638e-01, 9.76636410e-01],
       [6.66856408e-01, 6.35197401e-01, 2.54219532e-01, ...,
        8.41227889e-01, 6.34982586e-02, 3.93311262e-01],
       [5.95684290e-01, 4.42870855e-02, 5.36375642e-01, ...,
        2.26654172e-01, 5.57364345e-01, 9.81157064e-01],
       [5.78388691e-01, 1.63654089e-02, 7.87641525e-01, ...,
        5.97105265e-01, 2.61798263e-01, 9.82278943e-01],
       [6.80642247e-01, 8.64217877e-01, 1.07351184e-01, ...,
        4.87565994e-04, 9.33412552e-01, 5.38791537e-01]], dtype=float32)>

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [22]:
mat_mul = tf.linalg.matmul(tf1, tf2, transpose_a=False, transpose_b=True)
mat_mul

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.3908  , 72.07866 , 73.48688 , 72.866516, 74.72468 ],
       [84.36606 , 77.318985, 79.25997 , 75.878845, 78.96509 ],
       [79.15996 , 74.86331 , 74.79949 , 75.579254, 74.9893  ],
       [85.20123 , 81.32399 , 81.15618 , 78.0764  , 81.05906 ],
       [79.14336 , 76.85788 , 77.99496 , 75.52966 , 75.797165]],
      dtype=float32)>

Multiply the two tensors you created in 3 using dot product.

In [24]:
tf.tensordot(tf1, tf.transpose(tf2), axes = 1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.3908  , 72.07866 , 73.48688 , 72.866516, 74.72468 ],
       [84.36606 , 77.318985, 79.25997 , 75.878845, 78.96509 ],
       [79.15996 , 74.86331 , 74.79949 , 75.579254, 74.9893  ],
       [85.20123 , 81.32399 , 81.15618 , 78.0764  , 81.05906 ],
       [79.14336 , 76.85788 , 77.99496 , 75.52966 , 75.797165]],
      dtype=float32)>

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [78]:
tf_random = tf.random.uniform(shape=[224,224,3], minval=0, maxval = 1)
tf_random

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[1.3789880e-01, 4.1559017e-01, 7.2211385e-01],
        [1.6739309e-01, 5.2545452e-01, 7.2191298e-01],
        [7.7589262e-01, 1.6143703e-01, 7.4247444e-01],
        ...,
        [9.6981454e-01, 6.9088745e-01, 8.2151473e-01],
        [4.0783536e-01, 2.8745139e-01, 5.9122860e-01],
        [4.2396140e-01, 4.6285331e-01, 9.3328691e-01]],

       [[9.3200660e-01, 1.2352574e-01, 4.4805491e-01],
        [5.2641308e-01, 7.7343225e-02, 8.0505383e-01],
        [6.8567872e-01, 5.1807880e-01, 6.1314094e-01],
        ...,
        [9.8988020e-01, 8.0083513e-01, 7.6455891e-01],
        [8.6703813e-01, 1.7610645e-01, 3.2413316e-01],
        [2.6510465e-01, 3.0483723e-02, 4.9457920e-01]],

       [[6.8132138e-01, 2.2464180e-01, 4.7343087e-01],
        [5.0287759e-01, 4.9911845e-01, 4.1840398e-01],
        [5.6134498e-01, 5.3679943e-04, 5.7394004e-01],
        ...,
        [8.0451465e-01, 7.6471269e-01, 4.7916818e-01],
        [9.8646259e-01

7. Find the min and max values of the tensor you created in 6.

In [79]:
min_tf = tf.argmin(tf_random)
min_tf

<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
array([[112, 182, 106],
       [153,  11, 204],
       [  4,   2, 123],
       [178,   3,  46],
       [ 71,  15,  30],
       [ 17, 146,  88],
       [ 75,  83,  34],
       [166, 198, 196],
       [131, 107, 213],
       [ 43, 109,  74],
       [193,  67, 111],
       [ 17,  16,  35],
       [171,  60, 157],
       [ 82, 155, 188],
       [139,   2, 111],
       [ 27,  66,  16],
       [178,   4, 202],
       [ 80, 115, 113],
       [176,  74,   8],
       [104,  28, 129],
       [ 76,  29,  64],
       [126, 206, 160],
       [ 79, 176, 185],
       [ 91,  43, 174],
       [ 10,  29,  92],
       [116, 216, 138],
       [ 91, 101,  72],
       [151, 131, 217],
       [ 38,  71, 160],
       [169, 162, 165],
       [ 16,  84, 129],
       [ 35, 123, 167],
       [ 52,  55,  55],
       [ 95, 215, 168],
       [180, 109, 111],
       [104,  79, 160],
       [ 16, 188, 174],
       [138, 218, 170],
       [102,  78,  22],
       [ 38,  16

In [88]:
tf.reduce_min(tf_random)

<tf.Tensor: shape=(), dtype=float32, numpy=3.9339066e-06>

In [89]:
tf.reduce_max(tf_random)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9999974>

In [29]:
min_tf.shape

TensorShape([224, 4])

8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]

In [55]:
tf_create = tf.random.uniform(shape=[1,224,224,3], minval=0, maxval = 1)
(tf.squeeze(tf_create)).shape

TensorShape([224, 224, 3])

9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [73]:
from numpy import random
tf_create = random.randint(100, size=10)
tf_create = tf.constant(tf_create)
tf_create

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 5, 73, 62, 30, 51, 40, 37, 99, 89, 31])>

In [74]:
tf.argmin(tf_create).numpy()

0

10. One-hot encode the tensor you created in 9.

In [77]:
tf.one_hot(tf_create,depth=100)

<tf.Tensor: shape=(10, 100), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.,