1. Deep learning can be used in scenarios where the environment continuously changes. DL is adaptive. 
2. If a problem can besolved with a simple rule based approach then try to solve it without using ML/DL.
3. Outputs of deep learning aren't always predictable. 
4. Deep Learning models require a fairly large amount of data.
5. Deep Learning performs bet on unstructured data.
6. Data should be first converted into numerical form before giving it to neural networks.


In this notebook the following things are covered
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and Numpy
* Using @tf.function (a way to speed up regular python functions)
* Using GPUs with Tensorflow (or TPUs)



### Introduction to Tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector= tf.constant([2,4,6,14])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 2,  4,  6, 14], dtype=int32)>

In [5]:
# Check the dimensions of a vector
vector.ndim

1

In [6]:
# Create a matrix (more than one dimension)
matrix = tf.constant([[2,3],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 4]], dtype=int32)>

In [7]:
# Check the dimensions of a matrix
matrix.ndim

2

In [8]:
another_matrix = tf.constant([[1,2],[3,4],[5,6]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [9]:
# Eventhough we have 3 rows the dimension is still 2
another_matrix.ndim

2

In [10]:
# Create a tensor
tensor = tf.constant([[[2],[3]],[[4],[5]]])
tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]], dtype=int32)>

In [11]:
tensor.ndim

3

Scalar - a single number

Vector - a number with direction (eg: Wind speed and direction)

Matrix - a 2 dimesnional array of numbers

Tensor - an n-dimensional array of numbers (where n can be anything, a 0 dimensional tensor is a scalar, a 1 dimensional tensor is a vector

### Creating a tensor with `tf.Variable`

In [12]:
# Create a changeable tensor and unchangeable tensor
# unchanged tensor cant be altered
changeable_tensor = tf.Variable([1,2])
unchangeable_tensor = tf.constant([1,2])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>)

In [13]:
changeable_tensor[0]
# This will throw an error
# changeable_tensor[0] = 4

# This will not throw an error
changeable_tensor[0].assign(3)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 2], dtype=int32)>

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers 

In [14]:
# Random tensors
# We use seed in order to get reproducibility
# As we can see after using the equality operator the 2 random tensors are equal because we have initialised them with seed

random1 = tf.random.Generator.from_seed(3)
random1 = random1.normal(shape=(3,2))
random2 = tf.random.Generator.from_seed(3)
random2 = random2.normal(shape=(3,2))
random1, random2, random1 == random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.43640924, -1.9633987 ],
        [-0.06452483, -1.056841  ],
        [ 1.0019137 ,  0.6735137 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.43640924, -1.9633987 ],
        [-0.06452483, -1.056841  ],
        [ 1.0019137 ,  0.6735137 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in the tensor     
               This ensures that the neural network learns properly. Suppose there are 15000 images and the first 10000 images are cats and the last 5000 are dogs. Then in this case the neural network will become very comfortable thinking that it has to learn only cats and it might not provide very good results

In [15]:
not_shuffled = tf.constant([[1,2],[3,4],[5,6]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [16]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4]], dtype=int32)>

If we want to set our shuffled tensors in the same order we have to use both the global level random seed as well as the operation level random seed. 

> "If both the global and operation seed are set: Both seeds are used in conjunction to determine the random sequence."

In [17]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

### Other ways to create Tensors

In [18]:
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [19]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

### Turn numpy array into tensors                                         
         The main difference between numpy arrays and Tensorflow tensors is that the tensors can be run on GPU(which makes faster numerical calculations)

In [20]:
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [21]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [22]:
B = tf.constant(numpy_A, shape=(2,3,4))
C = tf.constant(numpy_A, shape=(3,8))
B,C

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

### Getting information from tensors

1. Shape
2. Rank
3. Axis or dimension
4. Size

In [23]:
rank_4_tensor = tf.constant([ [ [[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]] ], [[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]] ])
rank_4_tensor.ndim

4

In [24]:
rank_4_tensor[0]

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [25]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 2, 2, 3]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=24>)

In [26]:
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank)", rank_4_tensor.ndim)
print("Shape of a tensor", rank_4_tensor.shape)
print("Elements along the 0 axis",rank_4_tensor.shape[0])
print("Elements along the last axis",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor",tf.size(rank_4_tensor))

Datatype of every element: <dtype: 'int32'>
Number of dimensions (rank) 4
Shape of a tensor (2, 2, 2, 3)
Elements along the 0 axis 2
Elements along the last axis 3
Total number of elements in our tensor tf.Tensor(24, shape=(), dtype=int32)


In [27]:
print("Total number of elements in our tensor",tf.size(rank_4_tensor).numpy())

Total number of elements in our tensor 24


### Indexing tensors
Tensors can be indexed like python lists

In [28]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [29]:
# To get the first 2 elements of all dimensions
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[ 1,  2],
         [ 4,  5]],

        [[ 7,  8],
         [10, 11]]],


       [[[13, 14],
         [16, 17]],

        [[19, 20],
         [22, 23]]]], dtype=int32)>

In [30]:
rank_4_tensor.shape

TensorShape([2, 2, 2, 3])

In [31]:
rank_4_tensor[:1, :1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=int32, numpy=array([[[[1]]]], dtype=int32)>

In [32]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 2, 1), dtype=int32, numpy=
array([[[[1],
         [4]]]], dtype=int32)>

In [33]:
rank_4_tensor[:1, :, :1, :1]

<tf.Tensor: shape=(1, 2, 1, 1), dtype=int32, numpy=
array([[[[1]],

        [[7]]]], dtype=int32)>

In [34]:
rank_4_tensor[:, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=int32, numpy=
array([[[[ 1]]],


       [[[13]]]], dtype=int32)>

In [35]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([[2,3],[3,4]])
rank_2_tensor.shape

TensorShape([2, 2])

In [36]:
# To get last element in every row for rank_2_tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [37]:
# Add in extra dimension for the tensor -----> tf.newaxis
rank_3_tensor = rank_2_tensor[:, :, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[3],
        [4]]], dtype=int32)>

In [38]:
# The 3 dots(...) signifies every axis before the last one. We can use that instead of explicitly mentioning every single axis 
# like the above example
rank_3_tensor2 = rank_2_tensor[..., tf.newaxis]
rank_3_tensor2

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[3],
        [4]]], dtype=int32)>

In [39]:
# Alternate method
# axis = -1 means to expand the final axis
tf.expand_dims(rank_2_tensor, axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[3],
        [4]]], dtype=int32)>

In [40]:
# Expand 0th axis
tf.expand_dims(rank_2_tensor, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 3],
        [3, 4]]], dtype=int32)>

In [41]:
tf.expand_dims(rank_2_tensor, axis = 1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[2, 3]],

       [[3, 4]]], dtype=int32)>

### Manipulating tensors(tensor operations)
**Basic Operations**

`+`, `-`, `*`, `/`

In [42]:
tensor = tf.constant([[1,2],[23,4]])
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [13, -6]], dtype=int32)>

In [43]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 10,  20],
       [230,  40]], dtype=int32)>

In [44]:
# For faster performances in GPU. use tensorflow's built-in functions
tf.multiply(tensor,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  5,  10],
       [115,  20]], dtype=int32)>

### Matrix multiplication

In [45]:
  tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  2],
       [23,  4]], dtype=int32)>

In [46]:
# matrix multipication in tensorflow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 47,  10],
       [115,  62]], dtype=int32)>

In [47]:
# Element wise multiplication
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  1,   4],
       [529,  16]], dtype=int32)>

In [48]:
# Matrix multiplication in python
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 47,  10],
       [115,  62]], dtype=int32)>

In [49]:
matrix = tf.constant([[1,2,3],[4,5,6]])
tf.reshape(matrix, shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

Transpose and reshape yield different results

In [50]:
# Transpose of a matrix
tf.transpose(matrix)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [51]:
# Other way to multiply matrices
tf.tensordot(matrix, tf.transpose(matrix), axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [52]:
tf.tensordot(matrix, tf.transpose(matrix), axes = 0)

<tf.Tensor: shape=(2, 3, 3, 2), dtype=int32, numpy=
array([[[[ 1,  4],
         [ 2,  5],
         [ 3,  6]],

        [[ 2,  8],
         [ 4, 10],
         [ 6, 12]],

        [[ 3, 12],
         [ 6, 15],
         [ 9, 18]]],


       [[[ 4, 16],
         [ 8, 20],
         [12, 24]],

        [[ 5, 20],
         [10, 25],
         [15, 30]],

        [[ 6, 24],
         [12, 30],
         [18, 36]]]], dtype=int32)>

Generally during matrix multiplication if one of the matrice's shape has to be changed we use transpose instead of reshape.


### Changing the datatype of a tensor

In [53]:
A = tf.constant([1,2])
A.dtype

tf.int32

In [54]:
B = tf.constant([1.2,3])
B.dtype

tf.float32

In [55]:
# Change from float32 to float16
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 3. ], dtype=float16)>

### Aggregation 

Aggregating tensors = condensing them from multiple values down to a smaller amount of values. 

In [56]:
D = tf.constant([-1,-3])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -3], dtype=int32)>

In [57]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

1. Get the minimum.
2. Get the maximum.
3. Get the mean of the tensor
4. Get the sum of the tensor

In [58]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([67, 37, 30, 64,  1, 10, 37, 94, 63, 34, 15, 63, 84, 41, 69, 30,  5,
       28, 82, 76, 18, 80, 86, 42, 14, 16, 73, 36,  3, 75,  9, 70, 32, 99,
       85, 44, 14,  2, 43, 29, 81, 87, 28, 67, 58, 89, 37, 22, 54,  7])>

In [59]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [60]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [61]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [62]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2330>

In [63]:
# Find variance
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=831>

In [64]:
# Another method for variance
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=831.32>

In [65]:
# Find standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.83262>

### Find the positional minimum and maximum
  This example can be used while predicting the probabilities. For example our neural network classifies an image into cat, dog and goat. So for every image we get the probability of an image being cat, dog and goat. The attribute with the highest probability will more likely be in the image. For this case we use positional minimum and maximum. We find the index of the maximum element and alot the class according to it.

In [89]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [90]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [91]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [92]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [93]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor(removing all single dimensions)
Removes all dimensions with size 1

In [96]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [98]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [99]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [100]:
G_squeezed.shape

TensorShape([50])

### One hot Encoding

In [101]:
# Create a list of indices
some_list = [0,1,2,3] # Could be red, blue, green, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [105]:
# Reducing depth by one will save as from dummy variable trap
tf.one_hot(some_list, depth=3)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

In [108]:
# Instead of one and zero we can have whatever variable we 
tf.one_hot(some_list, depth=4, on_value='cat', off_value='not a cat')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'cat', b'not a cat', b'not a cat', b'not a cat'],
       [b'not a cat', b'cat', b'not a cat', b'not a cat'],
       [b'not a cat', b'not a cat', b'cat', b'not a cat'],
       [b'not a cat', b'not a cat', b'not a cat', b'cat']], dtype=object)>

### Math functions  --->   Squaring, log, square root 

In [109]:
 H = tf.range(1,10)
 H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [110]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [116]:
# For square root and log we have to give give tensor in the form of float or complex.
#  It doesn't accept int32 
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [117]:
tf.math.log(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy arrays

In [118]:
# Create a tensor directly from a Numpy array
J = tf.constant(np.array([3.,4.,5.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 4., 5.])>

In [119]:
# Create the tensor back to numpy array
np.array(J), type(np.array(J))

(array([3., 4., 5.]), numpy.ndarray)

In [120]:
# To access third element in our tensor
Q = tf.constant([1,4,5,2,51])
Q[2].numpy()

5

In [121]:
# The default types of each are different
numpy_J = tf.constant(np.array([3.,4.,5.]))
tensor_J = tf.constant([3.,4.,5.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)